src/components/common/Checkbox.tsx

close #24 
<br/>
ListBox 밀림 오류 해결
- Checkbox 스타일 수정
<br/>
<br/>

[Fix] ListBox 밀림 오류 해결

---

src/app/layout.tsx
src/app/page.tsx
src/components/common/Button.tsx
src/components/common/Card.tsx
src/components/common/Checkbox.tsx
src/components/common/CustomInput.tsx
src/components/common/ListBox.tsx
src/components/common/Tabbar.tsx
src/components/home/Todo.tsx
src/components/news/HomeGuide.tsx
src/components/school/home/HomeGuideRemind.tsx
src/components/signin/SocialKakao.tsx
src/data/commonData.ts

close #30
<br/>
공통 컴포넌트 리팩토링 및 수정사항
- input 배경 스타일 추가
- cusor: pointer 추가
- 메인 화면 이미지 로딩 이슈
- 공통 컴포넌트 전체적인 리팩토링
<br/>
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/b3aaf9c5-9105-49ba-af43-c48c5a91a1c8
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/bffc1134-69ed-4dd0-ad41-40dce2a81700
<br/>
- 우선 background 로딩 오래 걸리는 부분은 Image 태그 통해 해결했습니다. Image 태그의 경우 layout: fill 로 하면, sizes 기본 설정이 100vw로 되어있어있다고 해요. position: absolute가 기본이라 처음 로딩시 크기가 부모에 맞추어 커졌다 다시 돌아오는 것 같아요. 그래서 저는 width랑 height를 주고, 스타일 속성 넣어서 부모에 맞게 100%로 지정되도록 했어요! 근데 그래도 처음 로딩시에는 지정된 가로세로로 로딩되어 바로 원래 화면처럼 딱 안 나오는 문제가 있습니다!
- 전체적으로 주요 공통 컴포넌트들 리팩토링 했는데, 기능상으로는 달라진게 없을 거 같아요!
<br/>

[Refactor] 공통 컴포넌트 리팩토링 및 수정사항

---

src/app/mypage/children/page.tsx
src/components/common/Calendar.stories.tsx

close #46
<br/>
children 페이지명 변경
<br/>

[Fix] 배포 오류

---

src/app/mypage/children/page.tsx

close #46 
<br/>
Deploy 오류 - 페이지명 수정
<br/>

[Fix] Deploy 오류 - 페이지명 수정

---

src/app/mypage/children/page.tsx

close #46
<br/>
Deploy 오류 - export 제거
<br/>

[Fix] Deploy 오류 - export 제거

---

src/app/mypage/profile/page.tsx
src/app/mypage/profile/signature/page.tsx

close #46
<br/>
Deploy 오류 - Signbox export 제거
<br/>

fix(#46): Deploy 오류 - Signbox export 제거

---

src/app/signin/process2/page.tsx

close #46
<br/>
checkBox 오타 수정
<br/>

[Fix] Deploy 오류 - checkBox 오타 수정

---

src/components/common/ListBox.tsx

close #47 
<br/>
Deploy 오류 - ListBox props 수정
<br/>

[Fix] Deploy 오류 - ListBox props 수정

---

src/app/auth/page.tsx

close #46
<br/>
Deploy 오류 - window 객체 예외처리
<br/>

[Fix] Deploy 오류 - window 객체 예외처리

---

src/app/auth/page.tsx

close #46
<br/>
Deploy 오류 - window 오류 처리
<br/>

[Fix] Deploy 오류 - window 오류 처리

---

src/app/layout.tsx
src/components/common/NOSSR.tsx

- close #62
<br/>
SSR 스타일링 풀리는 현상 해결 
<br/>
<br/>
<br/>

[Fix] SSR 스타일링 풀리는 현상 해결

---

src/app/signin/process3-1/page.tsx
src/app/signin/process3/page.tsx
src/app/signin/process4/page.tsx
src/components/signin/SelectionPopup.tsx
src/redux/slices/userSlice.ts

- close #69
<br/>
- registrationToken에 Bearer 를 추가하여 요청 보내는 것으로 수정했습니다.
- `elementSchoolClass`를 `elementSchoolClassNumber`로 변경했습니다.
<br/>
<br/>
학교 찾기 API 연동을 아직 못해서 elementSchoolId를 임시로 설정해놨습니다.
또한, elementSchoolClassNumber 불러오는 API가 아직 미완성이라 "1"반을 보내는 것으로 임시 설정해놨습니다.
연동하면 바로 수정해놓겠습니다.
<br/>

[Fix] 회원가입 로직 수정

---

src/apis/school/getShcool.tsx
src/app/signin/process3/page.tsx
src/interface/School.ts
src/redux/slices/userSlice.ts

- close #66
<br/>
- 키워드로 학교 검색 API 연동
<br/>
<br/>
두번 클릭해야 검색 박스가 사라지는 것을 볼 수 있는데 
아직 에러 해결하지 못했습니다..
<br/>

[Feat] 키워드로 학교 검색 API 연동

---

src/apis/timetable/getWeekTimetable.tsx
src/app/school/page.tsx
src/components/school/home/TimeTable/TimeBox.tsx
src/components/school/home/TimeTable/TimeTableBox.tsx
src/interface/Timetable.ts

- close #67 
<br/>
- 시간표 디자인 추가
- 이번주 시간표 API 연동
<br/>
<br/>
response가 좀 복잡해서 아직 연결은 안 해놨는데
<br/>

[Feat] 이번주 시간표 API 연동

---

src/data/mypageData.ts
src/data/schoolData.ts

- close #82
<br/>
- 결석 사유서 작성 내역 학생 정보
- 마이페이지 수정 완료 toast
- 학급앨범 제목 더미 텍스트 반영
<br/>
<br/>
아직 추가로 1차 QA 더 진행할 예정입니다.
<br/>

[Fix] QA 1차

---

src/components/school/parentReference/FormPopup.tsx

close #86
<br/>
Calendar 컴포넌트 사용시 placeholder 제거

[Fix] 배포 오류 수정 - placeholder 제거

---

src/apis/axios.ts
src/app/mypage/profile/signature/page.tsx
src/app/signin/process3/page.tsx
src/components/home/AddTodoPopup.tsx
src/components/home/MealTable.tsx
src/components/home/Notification.tsx
src/components/home/TimeTable.tsx
src/components/school/notification/LastNotifications.tsx
src/components/school/notification/TitleBox.tsx
src/components/school/notification/TodayNotification.tsx

close #86
<br/>
token 변경
<br/>

[Fix] token 변경

---

src/apis/axios.ts
src/app/mypage/profile/page.tsx
src/app/mypage/profile/signature/page.tsx

[Fix] 배포 및 토큰 이상 오류

---

src/apis/auth/postKakaoToken.tsx
src/apis/axios.ts
src/apis/school/getShcool.tsx
src/apis/user/postUser.tsx
src/app/auth/page.tsx
src/app/signin/process4/page.tsx

- close #93
<br/>
로그인 에러 해결
<br/>
<br/>
리뷰어가 특별히 봐주었으면 하는 부분이나 주의사항, 알림사항 등이 있다면 작성해주세요.
<br/> ex) 더미 데이터를 넣어서 기능 구현한 상태입니다!
<br/>

[Fix] 로그인 에러 해결

---

src/apis/axios.ts
src/app/signin/process4/page.tsx

[Fix] localStorage 오류 수정

---

src/app/news/eduOffice/page.tsx
src/app/news/school/page.tsx
src/components/news/Summary.tsx
src/components/news/SummaryCard.tsx

close #96 
<br/>
교육청 상세 보기 수정
<br/>

[Fix] 교육청 상세 보기 수정

---

src/components/school/notification/Notification.tsx
src/components/school/notification/TodayNotification.tsx

- close #95
<br/>
- 학급 알림장 오늘의 알림장 수정
<br/>
<br/>
리뷰어가 특별히 봐주었으면 하는 부분이나 주의사항, 알림사항 등이 있다면 작성해주세요.
<br/> ex) 더미 데이터를 넣어서 기능 구현한 상태입니다!
<br/>

[Fix] 학급 알림장 오늘의 알림장 수정

---

src/components/school/SchoolHomeTop.tsx

close #{이슈번호}
<br/>
이번 PR에서 작업한 내용을 간략히 설명해주세요.
<br/>
<br/>
리뷰어가 특별히 봐주었으면 하는 부분이나 주의사항, 알림사항 등이 있다면 작성해주세요.
<br/> ex) 더미 데이터를 넣어서 기능 구현한 상태입니다!
<br/>

fix(#96): 초등학생 이름 삭제

---

src/components/school/notification/TodayNotification.tsx

close #{이슈번호}
<br/>
이번 PR에서 작업한 내용을 간략히 설명해주세요.
<br/>
<br/>
리뷰어가 특별히 봐주었으면 하는 부분이나 주의사항, 알림사항 등이 있다면 작성해주세요.
<br/> ex) 더미 데이터를 넣어서 기능 구현한 상태입니다!
<br/>

fix(#96): 오늘의 알림장 수정

---

src/app/mypage/profile/page.tsx
src/app/mypage/profile/signature/page.tsx
src/app/news/eduOffice/page.tsx
src/app/news/school/page.tsx
src/app/school/notification/page.tsx
src/components/common/ListBox.tsx
src/components/common/ListNumber.tsx
src/components/home/MealTablePopup.tsx
src/components/news/SummaryCard.tsx

close #103 
<br/>
- 급식표 날짜 오류 해결
- 서명 localStorage 오류 해결
- 소식 : background, 하단 먹힘 해결
- 가정통신문 : ListBox background 컬러 적용 등
<br/>
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/5e1cf567-c6e6-4192-9bf0-f477a4d1cc9a
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/922b50fc-9e0f-4899-8cf5-7f78c2f05d28
<br/>

[Fix] 급식표 날짜 오류 및 서명 localStorage 오류 수정

---

src/app/mypage/children/page.tsx
src/app/school/parentReference/absentReason/form/page.tsx
src/app/school/parentReference/workStudy/form/page.tsx
src/components/common/Calendar.tsx
src/components/mypage/AllergyPopup.tsx
src/components/school/parentReference/FormPopup.tsx

close #117
<br/>
- 체험학습 신청서 작성 구현
- 마이페이지 알러지 설정 (모바일뷰 깨짐 수정)
- 알러지 수정하기 적용 (4개 이상 시 말줄임표 추가)
<br/>
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/4b6f047f-2d54-49cb-a046-d88b306adf88
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/0020701b-30d6-48aa-9efa-a412779eff78
https://github.com/Kusitms-29th-ASAP/Frontend/assets/102593738/610043f9-ec9d-4a6e-8277-9f9e1e5c5631
<br/>

[Feat] 체험학습 신청서 작성, 마이페이지 알러지 설정

---

src/components/mypage/AllergyPopup.tsx
src/components/school/notification/TodayNotification.tsx
src/data/allergyData.ts

close #123
<br/>
- allergiesDat 데이터 수정, 정렬 수정
- 오늘의 알림장 날짜 수정
<br/>
<br/>

[Fix] 알러지 조개류 반환 오류

---

src/components/home/MealTablePopup.tsx

close #126
<br/>
토요일 월간 급식표 처리
<br/>
<br/>

[Fix] 토요일 월간 급식표 처리

---

src/apis/auth/postKakaoToken.tsx
src/apis/school/getShcool.tsx
src/apis/user/postUser.tsx

close #128
<br/>
서버 주소 변경
<br/>
main으로 바로 올릴게요!
<br/>

[Chore] 서버 주소 변경

---

src/apis/axios.ts
src/app/home/page.tsx
src/app/mypage/page.tsx
src/components/common/ListBox.tsx
src/components/common/More.tsx
src/components/common/Popup.tsx
src/components/home/Notification.tsx
src/components/home/Todo.tsx
src/components/school/home/DateSelect.tsx
src/components/school/home/HomeGuideRemind.tsx
src/components/school/home/TimeTable/TimeTable.tsx
src/components/study/review/ReviewTitle.tsx
src/data/notifyData.ts

close #140
<br/>
- z-index 수정
- 어색한 줄바꿈 수정 및 자동 hyphens 추가
- 더미데이터 날짜 수정
- 잘못된 localStorage 값 변경
- axios interceptor로 헤더 적용 등
<br/>

[Fix] 웹 및 모바일 오류 수정 (CSS 위주)

---

src/apis/axios.ts
src/app/home/page.tsx
src/app/mypage/page.tsx
src/components/common/ListBox.tsx
src/components/common/More.tsx
src/components/common/Popup.tsx
src/components/home/Notification.tsx
src/components/home/Todo.tsx
src/components/school/home/DateSelect.tsx
src/components/school/home/HomeGuideRemind.tsx
src/components/school/home/TimeTable/TimeTable.tsx
src/components/study/review/ReviewTitle.tsx
src/data/notifyData.ts

[Deploy] ver. 2.0.0

---

src/components/common/ListBox.tsx
src/components/home/MealTablePopup.tsx
src/components/home/Todo.tsx

close #140
<br/>
- 급식표 컴포넌트 높이 auto로 수정
- 음성 변환 시 z-index 변화되게 수정
- ListBox 오류 수정
<br/>

[Fix] 수정사항 반영

---

src/components/school/weeklyStudy/WeeklyNotification.tsx

close #140
<br/>
주간 선생님 가정통신 더미데이터 내용 변경
6월 2주차 → 9월 1주차,
6/11 (화) 에는 ~ → 9/6 (금)에는 ~
<br/>
<br/>

[Docs] 더미데이터 내용 변경
